# Generated by Django 5.0.6 on 2024-08-25 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=11, unique=True, verbose_name='الرقم الوطني')),
                ('first_name', models.CharField(max_length=20, verbose_name='الاسم الاول ')),
                ('father_name', models.CharField(max_length=20, verbose_name='اسم الاب ')),
                ('last_name', models.CharField(max_length=20, verbose_name='النسبة  ')),
                ('mother_name', models.CharField(max_length=20, verbose_name='اسم الام ')),
                ('province', models.CharField(max_length=20, verbose_name='المحافظة ')),
                ('gender', models.CharField(max_length=20, verbose_name='الجنس ')),
                ('marital_s', models.CharField(max_length=20, verbose_name='الوضع الاجتماعي ')),
                ('place_number_of_registration', models.CharField(max_length=20, verbose_name='مكان ورقم القيد ')),
                ('date_of_birth', models.DateField(verbose_name=' تاريخ الميلاد')),
            ],
        ),
    ]
