# Generated by Django 5.0.6 on 2024-08-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaldata',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='marital_s',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='place_number_of_registration',
        ),
        migrations.RemoveField(
            model_name='personaldata',
            name='province',
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personaldata',
            name='national_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
